bulk = """http://upwpzxleikl.uzdybqzxfs.hu
http://tqmicjdxzamy.ychjoxdobcpr.biz
http://wukuobhxd.baqbnoalrh.br
http://fyugaj.cxuxholiwimn.cn
http://dlzrmljt.oyejfftc.sg
http://xeymqgiysv.fztfqfrz
http://oycydhrfpidu.pkmxjftr.de
http://kqjqhipfxn.vqpnwevz
http://ojoms.fjfxuvgkdpz.cn
http://nrjdgwalr.ktotham.eu
http://wgdqck.gabpnog.hu
http://mtsyksidhb.inmokssav.info
http://bdcqr.xnjkhcirvqv.info
http://hmgtbqmtqh.sjavasnxfwhn
http://evgayyhke.luoflwc.com.au
http://dafvnd.klojbtf.sg
http://dfcokdzfsfr.ivtlwzhjdj.tw
http://xdpriwlmc.anrasjgkyo.co.uk
http://zcrhluqfio.ygsusexgf.fr
http://gdhmnfbtxbvp.hkzmtnwr.tw
http://lmtjsytpf.xskdteauzpch
http://uspqk.ewvxfnwzd.biz
http://btgemkehkuj.ullnbcxkgtg.info
http://uzyybuzvbdil.pwdzoykal.de
http://jwjdd.cxmawouvj.br
http://rhigelfsjqtv.vezeidr.fr
http://ekxse.caruizamlge.br
http://xqatvzydcpnd.xanctpdljlk.fr
http://wrcroahotdos.rhuvcswp.br
http://eybokmyhi.kzekhtekiw.no
http://elvhd.wyibwkpgwno.com.au
http://yeijlb.wklnkqyfxb.ru
http://zguwrkcnyrs.pwkzimn.com.au
http://zsgpqlmskfs.aoikrviink
http://vythlydk.jahvmafssw.bg
http://edyamho.fyseszqqcahm.eu
http://hnpmfhjyo.cnooucmabe.com.au
http://eujhvqtwfa.unpcworkq.com.au
http://fzbsacwfvbaf.wwbsbcdw.net
http://zmhqwyvveu.wvytauuazdwv.com.au
http://xhsuxltjt.grebwzxsu.hu
http://vqgwqjsl.ijwbdtnwdh.co.uk
http://zlkvlin.ezbvfxlp.no
http://ezgaakuohxvn.uzrpkzdq.info
http://sziqk.hhbgochyxwfv.no
http://cmstcdtfuxi.wqchokoqq.info
http://ycquhllbny.gaxzfrwnete.sg
http://srpih.bguracclepk.ru
http://kvvqnsdslhz.aqbiytjeo.eu
http://qcqurb.nlpibcafumn.tw
http://nlzvjsfogftx.kszllnxa.br
http://dweyirsgedfa.ygbflvcugv.tw
http://ggphcnkyri.jannetor.no
http://txgpzavvunb.cjdqtci.biz
http://rcwfhqt.hoseuhevdapq.biz
http://tktjevrgfj.boprhozwh.com.au
http://ojlsjbjlrc.lmahegmnpobf.co.uk
http://tfgbkwqt.ickrnbujn.sg
http://ulqhzfvb.bkfhqgrnw.de
http://fogwcirmvxw.jnxittjevu.cn
http://lpuzm.vrucowkf.cn
http://dexmruu.nepiyyljo.co.uk
http://blesfgh.rmkypov.biz
http://qwreagm.fyjteruqwnwd.br
http://vhitwxpyefvv.wbwvhufaz.hu
http://ptjmwekrltl.qagugcqp.ru
http://muzhzagwvw.fimjsevmpd.biz
http://kxwmnmkfye.feemaaip.co.uk
http://cqkglwvoym.vjljwvouatae.ru
http://fyvuemwu.dftzurltnvew.no
http://lmben.cakavfei.biz
http://fffyezqqtemy.dymqard.co.uk
http://dqtzwyhzxn.cljccavg.org
http://hqsugsljyen.ymmwtlthqw.bg
http://yvaubmojdhej.psyufos.bg
http://omlit.embdhby.fr
http://mtrtxbtnu.hagzshnesvx.tw
http://kverx.bmoueis.com.au
http://fzvmz.lrjzwbu.tw
http://vdravpcxbrr.zkkcpjxb.cn
http://naimwkhqfdux.qmfnnwf.bg
http://pdzenwgwvtx.guonltq.co.uk
http://twdzjrvoks.oribopy.fr
http://wnprbcc.tinnfqmoiids.eu
http://hspigeh.nedcvffyby.sg
http://lmfyangdg.knzzwfdd.br
http://hytdeybfxi.jvzhvnnztuk.sg
http://jdynhufpsys.xucvcxexwmtj.eu
http://dudkonnnbv.gkaecxcw.eu
http://zycxuoreokhj.rybflcatil.tw
http://nrpksmkq.ildzpskwby.gov
http://zulbvejgywuq.fiypznykq.ru
http://ihxkg.kfgvgbaqi.ru
http://cozixyxxl.ictilbgwhsgn
http://uackj.ylpytnw.bg
http://iotlhbxj.traaezcz
http://kjgiuv.ojdgulun.ru
http://pumwo.xpjwriw.hu
http://fcbayhphlv.wqputeo.co.uk
http://dkyst.kbqhuvkvvid.de
http://ogslxhfqlt.mxglpzfabwhv.bg
http://rnauyrifkt.rytdspq.net
http://cfwhfxdntve.jfeiwnogg.no
http://fkcxatnwvtsd.qhmkcrumwzvt.org
http://ztayzkb.lvkhqdaudrbp.eu
http://gwqcvl.ivwcvubgwyrr.cn
http://imzcprdfshlo.okkksggvbbwi.ru
http://zpezyrzagqe.imxxlmhwx.eu
http://evefs.dnmtrlsik.bg
http://bxbkkzhwm.sjouojztbl.ru
http://xrhjjqucf.ahflhmhubzep.br
http://ztmbfkqdcx.lnhotcpbi.eu
http://vhdwhhl.alvmmbx.info
http://zarloy.ibpjjqt.com.au
http://wbfenifydrke.njooaadyal
http://vjgonekpk.csubwmmbba.fr
http://okqrjqdigy.mnfryvbnyui
http://ulrwlbmamd.vuveauwnhcf.co.uk
http://gtwbbvrwhiss.ftxjltdgy.com.au
http://usixx.vehrfjnwfu.com.au
http://mqefnnrgrxev.zoiwlwsqejvn.hu
http://sqxrdnvjaj.hbylxxk.de
http://hxczng.itgamxydb.de
http://kmjltkjfhhqt.yqpydvhlpo.org
http://lkfnw.xjnidysi.co.uk
http://zznxp.wtzefos.no
http://ecvrzapioy.nrutrusfs.cn
http://obhsgwl.npbihajwjyvu.de
http://pedkxjcf.rhzjovvmikn.bg
http://obpxzkskxi.bsmkvrbmzb.hu
http://wrafcoxuc.kzyvsisaxttk.com.au
http://bgbahxodp.jrchmfgwfe.bg
http://nkxlervifwog.vemztaikdqxi.hu
http://nallnwjyaau.fqwmosqb.no
http://baufqsom.bnynauwzu.hu
http://dckapzsfajp.kkibcwn.gov
http://bmlcghbbeveg.evgxbhhr.fr
http://bstdogsnie.klglnkhsroxn.tw
http://obbflthdmks.dfbhdltkxgu.com.au
http://mtwznqopsuam.ezmwspc.br
http://ggrqexlkwxds.rjlgcfhohlnt.cn
http://jkahrh.hmwswtpzmmrv.ru
http://xdfmlqzfzfok.wbouiaqb.hu
http://rwwdosbm.frcqibvhhk.no
http://gscabdrca.txyxlqz.ru
http://epjvxlq.tbwhhpki.no
http://atocnmaky.jwyolijitan.org
http://kuizf.qtrkhtxuui.bg
http://solgztqi.qwargvafar.hu
http://jgcddwylokd.wkcpakd.no
http://ejnajsb.ovlvxoy.tw
http://kixnktyn.yynqerzss.cn
http://tlzowuml.gydovrzppmy.gov
http://mepddhwn.pyseumqfgwe.fr
http://zbjorwng.zkwdoeab.hu
http://zptuckaih.sreubtmy.sg
http://fgdcksgktd.tsuoveo.info
http://twexqgrc.yukfymqq.tw
http://jxbdq.slahonakrybx.net
http://boyltw.jnrkxplafhtq.cn
http://fvbqm.sjpwldvxwsvg.com.au
http://qcccdikwz.weoxvbxolmk.hu
http://funxqtcdkf.mioxenpa.bg
http://yofvcq.mnyrhlpy.com.au
http://bpxhcfwzjj.kctiqzdspl.com.au
http://jxlumj.flpcsrhpqryf.biz
http://zkryn.oyqsineca.org
http://fyrir.qgzhffjhf.tw
http://dgjsfzlnnpqo.stbkctt.bg
http://tagzj.ecmijvbovm.biz
http://bsxdlrf.tyqlzjlfiusm.ru
http://vhbwww.ygjrdndu.bg
http://nrpzqzkwhfou.upkvmgs.br
http://yewbrz.jzjbpirotnw
http://qcwgm.ttknyirvjiv.com.au
http://uoukwmypzv.clqzsdrlwc
http://krqtzlysgmn.jzpyzkmbwc.biz
http://ftbcvaxfr.zrzykfkxwu.hu
http://svxexthy.nrkpnknsc.eu
http://tzqdfbbcvx.nslspfaopo.co.uk
http://dtkrmmrefrvj.wkzshofaayqg
http://vnlurf.israxwrs.co.uk
http://pqohycnzc.pilvdzgyq.org
http://zeuzcr.uxgkourmxfl
http://bidxlcektq.svhsxzjswq.info
http://kvxhajhr.puibxmlqd
http://yhbwgkp.bsnmnkt.gov
http://bgfqansyzeo.dxbkyyq.cn
http://tkhhwvrqj.rpqiqeaoe.com.au
http://hizjs.ijhwdrdknzcd.cn
http://vyedpjedn.gusgekemu.de
http://xdnhqmj.vxqtctjlymy.cn
http://taaxlfkfrtd.gkltugorwit.net
http://epedxywyyu.eeqvytqee.biz
http://yhmqeukumpjr.hppgojqsogn.de
http://dqefo.natrvdm.cn
http://vzldoakcka.yhikhlblqpo.info
http://hvmlhuedup.jprlzrgy
http://igbjsszhw.orcazxecst.cn
http://janjs.hrjpykzrczy.ru
http://npsnoqrri.ajvbweuqm.de
http://clkbcmaakpoa.bpytggfh.net
http://jnfdd.pdtaoudavel.de
http://mtubroiytq.uzczdgrtjk.tw
http://fxybbkmtwgoy.chwwylqynqbu.sg
http://dspcxmaynll.hrwgpyom.br
http://xlklclfk.jcvlzimy.hu
http://jdfbzmqyactm.fwmhisr.gov
http://tkots.soycsed.bg
http://uqqwkdxpzj.hcpwejhsdatv.net
http://yhwbzmvqds.gpqgzno.biz
http://lgmsy.trlijjpfkp.bg
http://fwzgcpw.okxqnjwac.br
http://vnbdxktcv.vcorbvuqr.info
http://cbwplt.nofibgmyrg.biz
http://pxoeppzj.rnmtpija.eu
http://opewrljqcpsp.pdjetioa
http://mtruc.vbglgddsmtu.biz
http://khanqfhy.hyutrmouekw.de
http://dozvasqceak.oakvzddx.ru
http://pkljpvgarjpr.pjvsovdt.fr
http://dfchiz.fpqqzgmf.sg
http://owvtmf.ftkinulqzn.ru
http://ndncudc.qhhvwdq.net
http://weuqpcdjn.ibsqpwdsqhu.no
http://bxsxbjnqgslw.naqbuzdn.net
http://jtlzafqygo.epasghlres.co.uk
http://jhzilm.evrpvrulpbzg.co.uk
http://hzvpkntct.maxulktqgkfb.biz
http://nrbnyhcggyvq.otfnffkar.br
http://hbemcgmqynd.vgdcfysrnmwa.bg
http://lttgn.hrokyaa.hu
http://etjlxlqwe.jrekkfwd
http://rakjo.hpveezynlvz.biz
http://ejbvnmgtjk.lbtvkiqsylw.biz
http://vqwrpyit.kpvxvpgf.cn
http://hcorkekjqh.bcbytqxck.com.au
http://aakwprcyj.axblclutt.com.au
http://vgtpxqsivfi.qemhgkrqkprv.bg
http://pkwvfs.zhzqahl.co.uk
http://iwvuecfvsp.klcnbnkxt.biz
http://skyikguqxdms.qvcmoswzezmg.org
http://dgzczkbiuhcl.fxydotga.sg
http://xhdxujkrmqrp.bqxvyagdge.biz
http://tvpudor.spebzvopm.info
http://oucjsc.wjvysotiix.ru
http://hppmr.ifevjjjemt.hu
http://jtyfsrtlz.ixcqmsc.info
http://ljmgtvp.iivxsovygnrs.org
http://bkwrxoubvfk.medbcmkx.fr
https://www.amazon.com/mlicnwcejq/eqhrsy/ipocthxpk/uorwg/
https://www.amazon.com/tqi/gbdfjubuhv/qznochxvnx/
https://www.amazon.com/pwo/mivaj/m/hpi/og/
https://www.amazon.com/cqitat/sfauwggpw/ujvojzpjp/fmmbogc/
https://www.amazon.com/us/
https://www.amazon.com/aycxcaaldd/jkthtqegl/eyjvktv/foqgmxv/
https://www.amazon.com/orsqdfdxrm/wn/qwmwirmwsp/fj/fksbu/
https://www.amazon.com/rktyffkplh/osaa/
https://www.amazon.com/attxz/
https://www.amazon.com/ol/wpki/
https://www.amazon.com/c/uboqarwy/ezq/u/mq/
https://www.amazon.com/q/bcptsg/yi/ouayyzhkbg/
https://www.amazon.com/eegx/fddbsalofa/
https://www.amazon.com/ojuqb/p/mdixrzfwgv/erttucdpkn/bpbdqio/
https://www.amazon.com/mca/gxpsynpbv/djn/iumww/
https://www.amazon.com/odiek/pjhzs/b/i/prlhum/
https://www.amazon.com/tysukbzysk/
https://www.amazon.com/v/vctopxyl/mohf/
https://www.amazon.com/sikpwtu/loxztcd/nr/
https://www.amazon.com/aqvdk/zeb/
https://www.amazon.com/dvwrdx/kjiyfanlb/kydmxamzr/erqhwo/rgnibczdkh/
https://www.amazon.com/xfsjpmuap/pefyzna/evxk/
https://www.amazon.com/he/bfpp/
https://www.amazon.com/p/
https://www.amazon.com/fyvooty/kywu/u/kituqvtwy/avolhr/
https://www.amazon.com/u/re/vgrg/
https://www.amazon.com/mn/kgoumjesxo/jb/
https://www.amazon.com/cibi/ttxsrs/pmj/fnn/
https://www.amazon.com/nq/
https://www.amazon.com/zociodkub/sduyn/ugii/li/hfe/
https://www.amazon.com/lzuchwq/zuorgusk/
https://www.amazon.com/ragekfazdc/rcv/lkapetvcej/
https://www.amazon.com/vc/hiiovzjxj/wvsl/kghlzl/fwstk/
https://www.amazon.com/d/t/hm/fxhlum/
https://www.amazon.com/xiwvhink/zvbafnye/naoguc/
https://www.amazon.com/cufcyhhlia/fsaxcpbp/yoyke/
https://www.amazon.com/nhamzcdyhg/
https://www.amazon.com/aekqq/kpolph/
https://www.amazon.com/wfuhpfwzue/kbfvlpdlvi/vmuqoj/shvnkzdjq/
https://www.amazon.com/dylay/w/
https://www.amazon.com/ehxwnwfbr/vffjtidfq/
https://www.amazon.com/gssecek/nhmla/b/zzdusmhf/
https://www.amazon.com/yyuhbkxct/jyje/pocmtvlmzu/
https://www.amazon.com/ueonak/ei/ejksel/dauspctv/ywnke/
https://www.amazon.com/ulzlfssmo/gzathoyzux/
https://www.amazon.com/dn/ruphgdrz/oyzxud/ax/j/
https://www.amazon.com/wecqha/u/fbvzfy/smrtxec/qrlvx/
https://www.amazon.com/ikwrqua/tugyb/d/
https://www.amazon.com/ug/gocxqthu/hnfrnljirh/
https://www.amazon.com/djrihdy/ovoywmtx/il/gz/fflyjls/
https://www.amazon.com/g/h/
https://www.amazon.com/qi/
https://www.amazon.com/bkutnfbcz/igwfzfa/
https://www.amazon.com/sbfjskth/jkmw/tigoqjikz/
https://www.amazon.com/duz/nvgrsu/ltnds/zkb/
https://www.amazon.com/ugnt/qkvorotk/
https://www.amazon.com/zrqbx/
https://www.amazon.com/tok/gbsgixmum/xugswbzfae/y/
https://www.amazon.com/qy/igbs/rpijnsiv/lhyjgs/jksktmvk/
https://www.amazon.com/wuw/rrkawjeta/s/ihiwgkax/
https://www.amazon.com/msrkigysne/yjpr/wuys/
https://www.amazon.com/fyh/vo/z/bleunuh/
https://www.amazon.com/vok/
https://www.amazon.com/kfmekvofz/cfb/ux/awtqgclp/
https://www.amazon.com/f/zthwxll/e/lyukojqro/
https://www.amazon.com/iicr/
https://www.amazon.com/joiwhocj/ilue/hfsrp/udhtdklxtg/
https://www.amazon.com/orqxcog/brqrypp/
https://www.amazon.com/po/f/
https://www.amazon.com/xcsz/
https://www.amazon.com/zknmjkzs/fgunrry/
https://www.amazon.com/nmejpxjuy/oim/fmlc/dwzgkxoxh/wjjixrjy/
https://www.amazon.com/w/
https://www.amazon.com/szmjb/swomaeqvt/zmkzx/meakboof/bp/
https://www.amazon.com/jffobip/c/ntjeusa/
https://www.amazon.com/a/
https://www.amazon.com/g/dgzdrdixf/goq/t/
https://www.amazon.com/rta/rrpswnfkut/yzkwydu/drhbwwsit/vtf/
https://www.amazon.com/lgtez/
https://www.amazon.com/wrhh/gzuqmvzgn/phlabmc/dnlpnwzd/
https://www.amazon.com/b/accn/
https://www.amazon.com/wmxyrnp/xkmdwhgfvf/
https://www.amazon.com/madvcf/lt/
https://www.amazon.com/twkwdi/
https://www.amazon.com/ej/
https://www.amazon.com/ixlan/mcrnszj/
https://www.amazon.com/kckxoqcpe/q/vipl/bdvnmiisbo/ryooix/
https://www.amazon.com/zrhcbsqtzr/fhlmlvn/txeqc/
https://www.amazon.com/ptxsflylsl/y/fgbkw/uron/sndl/
https://www.amazon.com/agl/eecgl/
https://www.amazon.com/a/wqcf/
https://www.amazon.com/ckrzkltnos/ryfxfsuwzd/dq/kzp/nuutmuk/
https://www.amazon.com/lckjjiacxn/vxce/tqez/xri/ez/
https://www.amazon.com/xbmna/igffieb/u/tvebehi/bgagoww/
https://www.amazon.com/s/
https://www.amazon.com/v/ph/tg/y/
https://www.amazon.com/mknwfz/
https://www.amazon.com/yaiycyw/ffczs/lqxrfqeha/igyzkmksa/sdiyrfirt/
https://www.amazon.com/os/
https://www.amazon.com/vufx/vlnbkbju/ixl/
https://www.amazon.com/fuoggt/ajratvdb/gwf/bqhydovf/nratjkn/
https://www.amazon.com/kq/ca/sudph/yzzsb/tfq/
https://www.amazon.com/wsxi/khrdtkfbcd/
https://www.amazon.com/dxrnv/
https://www.amazon.com/qeqk/
https://www.amazon.com/wvx/rgx/
https://www.amazon.com/zetjzm/jqapcxwnhl/sqfpdgk/
https://www.amazon.com/bn/
https://www.amazon.com/x/mod/fusqg/rnogzwavv/
https://www.amazon.com/spvhunf/
https://www.amazon.com/jcosfqf/egkqutcnwv/ia/zhw/
https://www.amazon.com/cbmtzzkbxr/bjrqldyqou/rdhuyap/tcfmdayc/oj/
https://www.amazon.com/qir/lybgjqqf/rr/
https://www.amazon.com/gpogbvmhwh/mkygc/jpknkid/
https://www.amazon.com/uamuojjiho/zliwjlipy/hdmepufs/
https://www.amazon.com/klvo/
https://www.amazon.com/fjffhatoe/vtvolmsgbq/
https://www.amazon.com/h/fnhwmp/
https://www.amazon.com/mhxtr/kky/n/katr/bgcg/
https://www.amazon.com/rctzxb/ijvmceet/j/zdqll/bmode/
https://www.amazon.com/wbwg/nczml/
https://www.amazon.com/olgqswirpy/rrsgpped/
https://www.amazon.com/uesbi/
https://www.amazon.com/agaijvjbf/
https://www.amazon.com/lgumf/yznzgir/
https://www.amazon.com/anpr/hqybyftbgg/
https://www.amazon.com/s/yxnc/zzrlyc/
https://www.amazon.com/e/fgb/vxh/mjikxdo/dak/
https://www.amazon.com/mtpzqcm/asnropvd/wrowzgwire/gtmiidadpv/
https://www.amazon.com/xbatn/zjwo/
https://www.amazon.com/ji/
https://www.amazon.com/vylwdohe/
https://www.amazon.com/kxmuxqjub/qs/no/pvdmuz/
https://www.amazon.com/vacdkew/
https://www.amazon.com/bjnjpulxfl/cf/ndiclhdqs/
https://www.amazon.com/jzd/
https://www.amazon.com/fbm/lyvwtoej/pthp/xufwzkisd/
https://www.amazon.com/df/dv/
https://www.amazon.com/gr/mauwsl/nmqqua/nnficxzrpx/
https://www.amazon.com/qsw/
https://www.amazon.com/etskvc/vtwyy/ruwikvo/
https://www.amazon.com/kvjelitn/yslcpzos/
https://www.amazon.com/zk/r/bwodb/qjzgyubvoj/vrprceka/
https://www.amazon.com/bniqjew/
https://www.amazon.com/gupacu/gnvoplfxvw/
https://www.amazon.com/mblcw/
https://www.amazon.com/wwrfph/znnvc/yfn/
https://www.amazon.com/ft/zpfoyrez/ktls/
https://www.amazon.com/qddwtayu/pcp/dlmspcczln/n/wo/
https://www.amazon.com/eyw/dsfyq/ldtqp/fptpqlxri/pmkbzor/
https://www.amazon.com/qwubtf/ilzozjb/gckggb/cyp/jzc/
https://www.amazon.com/zkvqnsr/nzpp/
https://www.amazon.com/v/a/o/zqmf/evfafodgnd/
https://www.amazon.com/ybgpv/uzy/zdspb/aecyzqhzxr/ptcfblpu/
https://www.amazon.com/mxx/ubtwo/gwvddvkud/
https://www.amazon.com/rtclnqbfiv/
https://www.amazon.com/xhpgndthjt/
https://www.amazon.com/uyh/bcz/olscvo/a/
https://www.amazon.com/lkjgit/mga/t/xlipwpqdc/qsi/
https://www.amazon.com/ziozfx/
https://www.amazon.com/tdbbhcr/
https://www.amazon.com/kdwxngz/deetllm/
https://www.amazon.com/rznjey/bvbxihuqiy/owugjmwly/rvi/nr/
https://www.amazon.com/kuqm/
https://www.amazon.com/uzpevml/nox/zj/ptjspfarj/yjygp/
https://www.amazon.com/inhdg/qirz/
https://www.amazon.com/q/junbpoti/fe/ggyrbeyizw/tqmwog/
https://www.amazon.com/t/
https://www.amazon.com/pmhcxwwcwi/vhyobwlu/kkbiwda/azakt/ajirvypnfn/
https://www.amazon.com/e/peqjfvy/
https://www.amazon.com/dlhnre/firxzmp/
https://www.amazon.com/fqxotpn/
https://www.amazon.com/adrbtplp/sdzj/vkhj/yhvubfgmn/hnqhnfy/
https://www.amazon.com/ozpozvxbga/
https://www.amazon.com/htbjmxuax/auymb/xdjelja/amooiqwaz/
https://www.amazon.com/hfid/opnkd/tmzojm/
https://www.amazon.com/pafk/xu/vnntovho/
https://www.amazon.com/ih/rxn/p/pfhcufij/
https://www.amazon.com/butzngzq/hr/
https://www.amazon.com/jydetpt/
https://www.amazon.com/nlajqpm/flaktopfd/
https://www.amazon.com/vo/qkctiz/byldprkbmu/tev/
https://www.amazon.com/ywgrlx/florqiwhk/
https://www.amazon.com/ahybdnta/exbbdvzhay/jhzfruevz/
https://www.amazon.com/z/m/ldoqmpvm/npmzxbbojw/vhar/
https://www.amazon.com/ibxhelb/e/kyvbjnwae/cn/llnc/
https://www.amazon.com/kog/wuqip/g/qhtgje/xbgnvteu/
https://www.amazon.com/c/vaphprzs/p/
https://www.amazon.com/ncm/yxm/swzshjod/
https://www.amazon.com/fpfvljxl/bwqm/
https://www.amazon.com/luxt/znybvo/nbtlnghb/k/sbwmtdefq/
https://www.amazon.com/emmfcoqi/hapshhee/
https://www.amazon.com/rzspb/vl/u/enolkszb/yoxofrpvva/
https://www.amazon.com/hjjn/
https://www.amazon.com/c/
https://www.amazon.com/bgawbxrfts/swlqhzzy/
https://www.amazon.com/bygewtjz/i/ghwv/mgxrnefyd/
https://www.amazon.com/ugqxdkfbl/vwpx/bdknoefelp/onpok/ewr/
https://www.amazon.com/nwrwavhep/greorhl/morbocd/iqbdwpql/fivvzpqz/
https://www.amazon.com/ohwqftqboq/zawnqk/zwwclvvx/pkhm/tuxvhasa/
https://www.amazon.com/bflomutwb/
https://www.amazon.com/juevn/qjkmpeml/
https://www.amazon.com/dw/fgzqsxxb/qjp/kfrzjmx/hftwp/
https://www.amazon.com/mtlscfj/oeypzwlp/fmwrwjlrq/
https://www.amazon.com/ikz/fme/cz/jdl/phqnm/
https://www.amazon.com/wryrzczva/tq/dsll/vfzith/vcpebo/
https://www.amazon.com/kixuzt/tsnav/wdickpflb/yfblz/
https://www.amazon.com/gkvljqviwx/ekxssvcpj/zzxmjbcfg/lqgjt/
https://www.amazon.com/jmjuwoqeey/trykmw/iwpjscrpw/
https://www.amazon.com/d/
https://www.amazon.com/brxzscbhis/
https://www.amazon.com/yehvwptm/dvzcap/qmsop/huccd/
https://www.amazon.com/ms/cpsbxjvoit/oho/wsdnfoxp/gnsvndh/
https://www.amazon.com/ykzai/gt/dgqtfipotr/hnyxlo/oxvrq/
https://www.amazon.com/klcvxegi/bbh/noygdna/xpnaiqp/pgegbbe/
https://www.amazon.com/injrs/ljkwwfnz/hqbsnida/amzb/
https://www.amazon.com/dmcy/myxvmrib/ykegwi/baggqxsiv/seymc/
https://www.amazon.com/nohq/wmh/paj/tokpcri/dxuqd/
https://www.amazon.com/ziorxkazgo/pkpdvxw/
https://www.amazon.com/kxaqoewdra/yx/skqpl/wdvuvjyq/g/
https://www.amazon.com/ejumlrekw/cgvyulxs/ren/nwys/tthhgdi/
https://www.amazon.com/ossmgoxwu/pme/
https://www.amazon.com/x/vrff/feiemj/
https://www.amazon.com/s/yaoqo/mwznlwv/bv/hwmxpuj/
https://www.amazon.com/ao/quajvjdnch/kqejflodpv/iwf/
https://www.amazon.com/snttut/i/
https://www.amazon.com/epd/ykmkm/kkdh/vcwru/dyoy/
https://www.amazon.com/hvcxnhmolw/kvqbr/sjqsphnqct/ksoslgnuec/
https://www.amazon.com/aobr/n/qnzlfttdml/
https://www.amazon.com/zdhnl/dyewxqroar/uljyxj/jkjql/
https://www.amazon.com/j/
https://www.amazon.com/rd/vizo/
https://www.amazon.com/cfo/nnhcdmruvt/rkgse/
https://www.amazon.com/wyozknvr/lztxlqja/rstwuxjk/ool/
https://www.amazon.com/gaxhwgj/ae/d/ezdgjz/
https://www.amazon.com/gxhs/
https://www.amazon.com/zcbih/fgbge/buqgijphlp/
https://www.amazon.com/bur/bbsgsxa/siumweiem/
https://www.amazon.com/nacnxydda/
https://www.amazon.com/fuctcmtdty/
https://www.amazon.com/aaib/zqjc/raoqnsna/lm/
https://www.amazon.com/yyrdela/eb/seaaaop/vvttmq/
https://www.amazon.com/cnavouc/
https://www.amazon.com/shrdfhrcgl/hvmfrelxy/jnlkgxogq/yznleto/
https://www.amazon.com/ekcuh/is/
https://www.amazon.com/dfheufmdmt/
https://www.amazon.com/iguj/vbebj/ujgmrforcp/tebibpw/jwu/
https://www.amazon.com/iulbrh/jmfshls/vyffuuys/
https://www.amazon.com/cp/
https://www.amazon.com/catzs/jaikrgrkk/as/gxug/eadhb/"""
rows = bulk.split("\n")
rows = ["\""+row+"\"" for row in rows]
data = "{\n\t\"urls\": [ "+" , ".join(rows)+" ]\n}"
print(data)

